int p1=8,p2=9,p3=10,p4=11,waitin=250,eston=500,final=2000;
void setup() {
  pinMode(p1,OUTPUT);
  pinMode(p2,OUTPUT);
  pinMode(p3,OUTPUT);
  pinMode(p4,OUTPUT);
 

}

void loop() {
  //0 
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);

  //1 
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);

  delay(eston);
  //2
  digitalWrite(p1,LOW);
  digitalWrite(p2,HIGH);
  delay(waitin);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //3
  digitalWrite(p1,HIGH);
  digitalWrite(p2,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //4
  digitalWrite(p3,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //5
  digitalWrite(p3,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //6
  digitalWrite(p3,HIGH);
  digitalWrite(p2,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //7
  digitalWrite(p3,HIGH);
  digitalWrite(p2,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //8
  digitalWrite(p4,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //9
  digitalWrite(p4,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //10
  digitalWrite(p4,HIGH);
  digitalWrite(p2,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //11
  digitalWrite(p4,HIGH);
  digitalWrite(p2,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //12
  digitalWrite(p4,HIGH);
  digitalWrite(p3,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //13
  digitalWrite(p4,HIGH);
  digitalWrite(p3,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //14
  digitalWrite(p4,HIGH);
  digitalWrite(p2,HIGH);
  digitalWrite(p3,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(eston);
  //15
  digitalWrite(p4,HIGH);
  digitalWrite(p2,HIGH);
  digitalWrite(p3,HIGH);
  digitalWrite(p1,HIGH);
  delay(waitin);
  digitalWrite(p1,LOW);
  digitalWrite(p2,LOW);
  digitalWrite(p3,LOW);
  digitalWrite(p4,LOW);
  delay(final);


}
